language: c

os:
    - linux
    - osx

compiler:
  - gcc

addons:
    apt:
      sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
      packages:
        - gcc-5
        - clang-3.7
        - g++-5
        - cmake
        - freeglut3
        - freeglut3-dev

script:
  - cmake .
  - make
