language: c

os:
    - linux
    - osx

compiler:
  - gcc

addons:
    apt:
      sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
      packages:
        - gcc-5

script:
  - cmake .
  - make
