language: c

os:
  - linux
  - osx

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

script:
  - cmake .
  - make
