# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/flash2/git/progswb2/trab/t2-172-9v7ywgw76tg2/robotfootball

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/flash2/git/progswb2/trab/t2-172-9v7ywgw76tg2/robotfootball

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flash2/git/progswb2/trab/t2-172-9v7ywgw76tg2/robotfootball/CMakeFiles /home/flash2/git/progswb2/trab/t2-172-9v7ywgw76tg2/robotfootball/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flash2/git/progswb2/trab/t2-172-9v7ywgw76tg2/robotfootball/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named robotfootball

# Build rule for target.
robotfootball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 robotfootball
.PHONY : robotfootball

# fast build rule for target.
robotfootball/fast:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/build
.PHONY : robotfootball/fast

SOIL/SOIL.o: SOIL/SOIL.c.o

.PHONY : SOIL/SOIL.o

# target to build an object file
SOIL/SOIL.c.o:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/SOIL.c.o
.PHONY : SOIL/SOIL.c.o

SOIL/SOIL.i: SOIL/SOIL.c.i

.PHONY : SOIL/SOIL.i

# target to preprocess a source file
SOIL/SOIL.c.i:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/SOIL.c.i
.PHONY : SOIL/SOIL.c.i

SOIL/SOIL.s: SOIL/SOIL.c.s

.PHONY : SOIL/SOIL.s

# target to generate assembly for a file
SOIL/SOIL.c.s:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/SOIL.c.s
.PHONY : SOIL/SOIL.c.s

SOIL/image_DXT.o: SOIL/image_DXT.c.o

.PHONY : SOIL/image_DXT.o

# target to build an object file
SOIL/image_DXT.c.o:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/image_DXT.c.o
.PHONY : SOIL/image_DXT.c.o

SOIL/image_DXT.i: SOIL/image_DXT.c.i

.PHONY : SOIL/image_DXT.i

# target to preprocess a source file
SOIL/image_DXT.c.i:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/image_DXT.c.i
.PHONY : SOIL/image_DXT.c.i

SOIL/image_DXT.s: SOIL/image_DXT.c.s

.PHONY : SOIL/image_DXT.s

# target to generate assembly for a file
SOIL/image_DXT.c.s:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/image_DXT.c.s
.PHONY : SOIL/image_DXT.c.s

SOIL/image_helper.o: SOIL/image_helper.c.o

.PHONY : SOIL/image_helper.o

# target to build an object file
SOIL/image_helper.c.o:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/image_helper.c.o
.PHONY : SOIL/image_helper.c.o

SOIL/image_helper.i: SOIL/image_helper.c.i

.PHONY : SOIL/image_helper.i

# target to preprocess a source file
SOIL/image_helper.c.i:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/image_helper.c.i
.PHONY : SOIL/image_helper.c.i

SOIL/image_helper.s: SOIL/image_helper.c.s

.PHONY : SOIL/image_helper.s

# target to generate assembly for a file
SOIL/image_helper.c.s:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/image_helper.c.s
.PHONY : SOIL/image_helper.c.s

SOIL/stb_image_aug.o: SOIL/stb_image_aug.c.o

.PHONY : SOIL/stb_image_aug.o

# target to build an object file
SOIL/stb_image_aug.c.o:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/stb_image_aug.c.o
.PHONY : SOIL/stb_image_aug.c.o

SOIL/stb_image_aug.i: SOIL/stb_image_aug.c.i

.PHONY : SOIL/stb_image_aug.i

# target to preprocess a source file
SOIL/stb_image_aug.c.i:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/stb_image_aug.c.i
.PHONY : SOIL/stb_image_aug.c.i

SOIL/stb_image_aug.s: SOIL/stb_image_aug.c.s

.PHONY : SOIL/stb_image_aug.s

# target to generate assembly for a file
SOIL/stb_image_aug.c.s:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/SOIL/stb_image_aug.c.s
.PHONY : SOIL/stb_image_aug.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/main.c.s
.PHONY : main.c.s

opengl.o: opengl.c.o

.PHONY : opengl.o

# target to build an object file
opengl.c.o:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/opengl.c.o
.PHONY : opengl.c.o

opengl.i: opengl.c.i

.PHONY : opengl.i

# target to preprocess a source file
opengl.c.i:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/opengl.c.i
.PHONY : opengl.c.i

opengl.s: opengl.c.s

.PHONY : opengl.s

# target to generate assembly for a file
opengl.c.s:
	$(MAKE) -f CMakeFiles/robotfootball.dir/build.make CMakeFiles/robotfootball.dir/opengl.c.s
.PHONY : opengl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... robotfootball"
	@echo "... SOIL/SOIL.o"
	@echo "... SOIL/SOIL.i"
	@echo "... SOIL/SOIL.s"
	@echo "... SOIL/image_DXT.o"
	@echo "... SOIL/image_DXT.i"
	@echo "... SOIL/image_DXT.s"
	@echo "... SOIL/image_helper.o"
	@echo "... SOIL/image_helper.i"
	@echo "... SOIL/image_helper.s"
	@echo "... SOIL/stb_image_aug.o"
	@echo "... SOIL/stb_image_aug.i"
	@echo "... SOIL/stb_image_aug.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opengl.o"
	@echo "... opengl.i"
	@echo "... opengl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

